#:schema node_modules/wrangler/config-schema.json
name = "dealwatch-worker"
main = "src/index.ts"
compatibility_date = "2025-09-27"
upload_source_maps = true

[observability]
enabled = true

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
# Every hour- https://cron.help/
crons = ["0 * * * *"]


[[kv_namespaces]]
binding = "KV"
id = "fc316cb39d40425cb9d03ed1bdf96eae"
